---
title: Blog Post 2
author: RRRRR
date: '2022-10-21'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-10-21T16:28:15-04:00'
featuredVideo: ~
featuredImage: ~
---
## Data Loading and Cleaning
Since our original data was in CSV format, we loaded it directly. Our group aims to find one specific continent and its accident numbers and factors that influence the accident rate. We consider all counties in Massachusetts as our main subjects to research, so as the original dataset is too big and contains all states and a lot of useless information, we try to clean and get the subset that focuses on the data from MA.

The original dataset we are working on has a lot of columns with unnecessary data, which results from missing information when collecting information from the report. We only want to work on the columns with valid info and important factors that might have related to the causes of the accident. So we first find how many missing rows and data are in our cleaned, mainly focused MA subsets; then we evaluate each column to decide which columns we want to keep for our research.

```{r}
suppressPackageStartupMessages(library(tidyverse)) 

#load data
HighwayRail<-read_csv(here::here("dataset-ignore", "Highway-Rail_Grade_Crossing_Accident_Data.csv"), show_col_types = FALSE )

#only keep data in MA
HighwayRail_MA <- HighwayRail %>% 
  filter(`State Name` == "MASSACHUSETTS") 

#select necessary column names for MA in original dataset
MA_select <- HighwayRail_MA %>%
  select(`Report Year`, Date,	Month, Day, Hour, Minute, `AM/PM`, Time, `Nearest Station`, 	Subdivision,	`County Name`, `State Name`,`Highway Name`,`Public/Private Code`, `Public/Private`, `Highway User`, `Estimated Vehicle Speed`,`Vehicle Direction`,	`Highway User Position`,`Equipment Involved`, `Equipment Struck`, Temperature, Visibility, `Weather Condition`, `Number of Locomotive Units`, `Number of Cars`, `Train Speed`, `Estimated/Recorded Speed`,	 `Train Direction`, `Crossing Warning Expanded 1`,`Crossing Warning Expanded 2`,`Crossing Warning Expanded 3`,`Crossing Warning Expanded 4`,`Crossing Warning Expanded 5`,`Crossing Warning Expanded 6`,`Crossing Warning Expanded 7`,`Crossing Warning Expanded 8`,`Crossing Warning Expanded 9`, `Crossing Warning Expanded 10`, `Crossing Warning Expanded 11`,	`Crossing Warning Expanded 12`,	`Signaled Crossing Warning Code`, `Signaled Crossing Warning`, `Roadway Condition`,	`Crossing Warning Location`,	`Warning Connected To Signal`, `Crossing Illuminated`,`User Age`,`User Gender`,`User Struck By Second Train`, `Highway User Action`, `View Obstruction`, `Driver Condition`, `Driver In Vehicle`, `Crossing Users Killed For Reporting Railroad`, `Crossing Users Injured For Reporting Railroad`, `Vehicle Damage Cost`,	`Employees Killed For Reporting Railroad`, `Employees Injured For Reporting Railroad`, `Passengers Killed For Reporting Railroad`, `Passengers Injured For Reporting Railroad`, Narrative)
head(MA_select, n=10)
```

